### ISSUE TITLE
Feature Request Merchant Shop

### ISSUE THREAD

**Issue by unrealkakeman89** [unrealkakeman89/sw5e#181]
Modify the backpack or actor item to allow GMs to put an unlimited number of items for sale into it, customize prices, and its contents visible to players. Players could then shop, look at item descriptions, select purchases, and then have the prices subtracted directly (and automatically) from their personal credits.  We could also add a haggle function that would allow the GM to modify the price manually (based on the agreement reached by the merchant and the player/s) that would be (automatically) deducted from the player's credits.  The item image could be used to display a photo of the establishment or the merchant or however else the GM would like to use it.

**Comment by SWpantus** [comment]
@unrealkakeman89 IMO modules like Monk's Enhanced Journal solve for this problem.

**Comment by unrealkakeman89** [comment]
True. I will close the issue.
