### ISSUE TITLE
Character import doesn't work at all

### ISSUE THREAD

**Issue by gravagehulk** [unrealkakeman89/sw5e#215]
I have tried generating a character at SW5e.com. I have tried importing the raw .json multiple ways (pasting the text in the box, right-click import, etc) and nothing seems to work. It just does nothing. Am I doing something wrong, or does this feature not work?

**Comment by jtljac** [comment]
Which foundry version are you running?
Are there any errors in the console?

**Comment by supervj** [comment]
You have to export the roll20 character from the sw5e website and then import that I to the sw5e in foundry.

**Comment by gravagehulk** [comment]
Ah, it never occurred to me that I'd have to export it as Roll20 first. Thank you. That was it!
