### ISSUE TITLE
Italian lang file

### ISSUE THREAD

**Issue by Parduz89** [unrealkakeman89/sw5e#220]
I translated the lang file in italian for personal use, but if there are people interested you may update the system-json to support it and add it to the repository.

[SW5e-ITA-main.zip](https://github.com/unrealkakeman89/sw5e/files/6664379/SW5e-ITA-main.zip)

**Comment by Parduz89** [comment]
edited, I can't figure out how to link the file, so I zipped it and uploaded it

**Comment by unrealkakeman89** [comment]
@Parduz89 We submitted an update and there are some tags that will need review on the it.json. When you get the chance would you mind reviewing, updating and submitting the file to me so I may push it to the master branch?
