### ISSUE TITLE
Manual Attributes resets

### ISSUE THREAD

**Issue by GrumpyVader** [unrealkakeman89/sw5e#241]
For our game we created new Races based on SW races in the Compendium. When we add the race to an Actor and then manually update one of the fields that are being increased by one of the Passive Effects values, it resets the next time you open that Actor. Also Ability checks and such do not reflect the new value. As a work around I found that if we remove the Passive Effect value, the manual changes are save to the actor. Let me know if you need more information.

**Comment by professorbunbury** [comment]
Thanks for reporting this issue, GrumpyVader.  Could you please identify the field you are trying to edit so that I can determine the best remedy?  Thank you!

**Comment by GrumpyVader** [comment]
My apologies for the delay, I had work and wanted to put together repeatable repro steps. So I determined that this issue also affects the Species in the Compendium. For the following repro steps I used Jawa but it seems to apply to app Species.

Repro Step:
1. Create new Actor
2. Open newly created Actor.
2. Update Ability Scores to desired value or leave at default value of 10. I left values at 10.
3. Open Species Compendium and choose desired Species. I used Jawa.
4. Drag desired Species over to open Actor sheet and verify Ability Scores were updated based on Species bonuses. Jawa has +2 to Dex and +1 to Int. Mine were 10, **12**, 10, **11**, 10, 10
5. Update value for Ability Scores. Updated mine to 10, **14**, 12, **13**, 16, 13.
6. Close Actor Sheet.
7. Reopen Actor Sheet.
8. Result: Ability Scores for the Species bonuses revert back to original value . Mine changed to 10, **12**, 12, **11**, 16, 13.

I hope this is enough detail. If not, let me know what else I can provide.

**Comment by professorbunbury** [comment]
I am sorry to report that, after numerous attempts, I have not been able to replicate the problem you are describing.  The best advice I can offer at this time is to make certain that you are using the current version of DAE that is appropriate for your version of Foundry.  Also, if you are hosting your Foundry installation remotely and you recently updated to SW5e version R1-A7, please make certain that it has updated properly on that remote server.  If these steps do not resolve the problem that you are experiencing, please respond to this issue thread.

**Comment by unrealkakeman89** [comment]
My recommendation is to go into DAE settings and 'suspend' the effects, make your sheet changes,  then go back to DAE settings and turn off the 'suspend' feature.
