### ISSUE TITLE
Species Ability Score Improvements blocking any updates to those ability scores

### ISSUE THREAD

**Issue by TiltedAiri** [unrealkakeman89/sw5e#246]
Like the title says, I have discovered through my character creation and leveling that ability scores that are increased by a species trait afterwards are locked/blocked from being updated after the species has been added. 

Tested it with many species but as an example. The Aleena species adds a +2 to Dexterity and a +1 to Charisma. if I try updating Charisma/Dexterity later when my characters sheets are finished and they're leveling up, it doesn't actually update. If I close the sheet and re-open it it has not saved it and it reverts to what it was before. 

Thanks for your hard work!

**Comment by unrealkakeman89** [comment]
There is an option in DAE settings to 'suspend' effects since it does take over auto calculating after there is an effect. You can use this to finish with the sheet then turn that feature off so that the effects activate again.
