### ISSUE TITLE
Powers Known cannot be edited and does not reflect actual powers known

### ISSUE THREAD

**Issue by gravagehulk** [unrealkakeman89/sw5e#265]
How can I fix this? I have a few players with this issue. One has force powers, the other tech powers. I think they have all of the features they are supposed to have. The "powers known" in the screenshot shows 5/0. When the player tries to cast a tech power, it tells him he doesn't have an available slot (presumably because of the "0". But I can't edit this, it doesn't come back on a long rest, and nothing I do in the system seems to grant him those slots.
<img width="881" alt="Screen Shot 2021-10-10 at 2 15 14 AM" src="https://user-images.githubusercontent.com/69117052/136687331-bb70650f-84b9-4b94-a1c2-e85453cce779.png">

Edit: So, I managed to change the /0 with DAE and it changes nothing. It's still looking for a 1st level spell slot, which doesn't exist. The only way I can fix this is by changing the spells to "innate" and manually setting them to consume tech points, unless I'm missing something.

**Comment by unrealkakeman89** [comment]
This is a known issue as it is not programmed into the system and will be coming soon. It is on our large list of things to add. Thank you.
