### ISSUE TITLE
Character sheet window cuts off Charisma by default

### ISSUE THREAD

**Issue by ProgLord** [unrealkakeman89/sw5e#312]
When opening a character sheet for the first time, it isn't big enough to show Charisma and you have to expand it manually. It seems to save the expanded size for that character, but if you sign back in, it will reset and needs to be expanded again. 

![Foundry Cha sheets](https://user-images.githubusercontent.com/37848523/153780695-758ed7c3-4b79-49f6-b641-66333885fe0c.png)
.

**Comment by SWpantus** [comment]
Note: Cannot reproduce on my instance (4k display).
