### ISSUE TITLE
Can't click arrows to change deployment rank on NPC sheet

### ISSUE THREAD

**Issue by SWpantus** [unrealkakeman89/sw5e#361]
![image](https://user-images.githubusercontent.com/100422816/160832483-d93a161f-4789-4663-a560-02b1fb83ac45.png)
![image](https://user-images.githubusercontent.com/100422816/160832497-e98f0634-d87f-4ce6-a67b-2942e05d1e09.png)

In the beta release for SoTG.
On an NPC character sheet, if you click the arrows to increase a deployment rank, you get an error.

**Comment by unrealkakeman89** [comment]
Is this still happening @SWpantus ?

**Comment by SWpantus** [comment]
Confirming - still an issue in the Dev-1.5.6 branch
