### ISSUE TITLE
SW5e tech powers & force powers, cast at level dialog doesn't display correct slots

### ISSUE THREAD

**Issue by TogaParty** [unrealkakeman89/sw5e#367]
When casting a tech power or force power, the 'cast at level' dialog shows 1000 slots instead of the correct number from the character sheet.

![image](https://user-images.githubusercontent.com/24837481/162062007-cb618a1b-465b-46d8-b716-1ca7b8e6b07d.png)

**Comment by unrealkakeman89** [comment]
The force/tech points and the Spell slots are different. We run off of DND5E core so we made unlimited spell slots (1000) since SW5e runs off of points.
