### ISSUE TITLE
Scholar Discovery: Mental Prowess missing

### ISSUE THREAD

**Issue by unrealkakeman89** [unrealkakeman89/sw5e#391]

**Comment by unrealkakeman89** [comment]
List under discoveries and not Maneuvers.

**Comment by Ikaguia** [comment]
So, it looks like academic superiority is listing all maneuvers and all discoveries, but discoveries is missing a few from the begining of the list
This is an issue with the importer, probably due to scholar being the odd one out, with 2 types of invocations (discoveries and maneuvers)
