### ISSUE TITLE
No equivalent to D&D5e attributes.ac.armor - attributes.ac.base or attributes.ac.flat don't seem to work with DAE

### ISSUE THREAD

**Issue by TogaParty** [unrealkakeman89/sw5e#422]
Looking at the "Way of Endurance".

This ability sets a base AC of 13 + con, essentially functioning as Mage Armor in D&D5e.  When attempting to configure this using attributes.ac.base or attributes.ac.flat, the calculations are not correct, Foundry returns values higher than they should be.

E.G. A character with a + 4 con modifier should have a base AC of 17 (it seems questionable whether or not they should get dex, I'm not sure).

DAE setup:
data.attributes.ac.base CUSTOM 13
data.attributes.ac.bonus ADD @abilities.con.mod

This character is giving me the following:
Natural Armor: 26
Equipped Armor: 10
Hide: 13

**Comment by TogaParty** [comment]
^ without also changing the AC calculation for the affected character.  Shouldn't equipped armor or natural armor return the correct value?

**Comment by unrealkakeman89** [comment]
No, Equipped armor and natural armor have their own calculation values stored in the config.js and DAE doesn't modify them. We are bringing the 1.6 core over soon and hopefully, that will get us on the same page as them.

**Comment by Ikaguia** [comment]
> That's what I'm doing to work around it, but that means the way of endurance ability cannot be correctly configured for other characters or NPCs.
@TogaParty what do you mean cannot be configured?
the method kakeman explained works both doing manually or using DAE, and should work on all both character and npc sheets
Aditionally, with the dnd5e 1.6 update ac.base has been replaced by @ac.armor, and cannot be overwritten by DAE as it is calculated based on your equipped armor (as expected)

**Comment by unrealkakeman89** [comment]
Since there is a way to use the custom formula to add the proper formula to the character sheet and there will not be a change in the 1.6 Core of the DND5e system, we will close this issue. Thank you
