### ISSUE TITLE
Blasters can't be reloaded, edited, or fired (ammo at /16), short rests restore -9 force points, lots of issues after update

### ISSUE THREAD

**Issue by jyurkiw** [unrealkakeman89/sw5e#468]
Updated to the lastest "stable" (1.6.2.2.2.2) from 1.5.something and the update screwed the whole game system.
![2022-06-17 19_35_03-Window](https://user-images.githubusercontent.com/372835/174419349-38b4901e-9a50-4436-83b3-3a7b92dc916f.png)
![2022-06-17 19_35_44-Window](https://user-images.githubusercontent.com/372835/174419351-b3759399-0396-46bc-8402-ff87ec8e69da.png)

The game system is basically un-usable after this update. All of our weapons that use ammo are broken, nobody can use any force or tech powers and a ton of other things we're running into.

Repro Steps:

- Install a 1.5.something
- Make a few characters
- Upgrade to 1.6.2.2.2.2
- Load into the game as a player
- Open your character sheet
- Try to shoot a blaster

Expected: you should either have ammo (I wasn't out of ammo last game) or should be able to press "reload" to reload your blaster.
Actual: You have no ammo, cannot reload, and adding new blasters to your inventory does not fix the problem (they have no ammo either and cannot be reloaded)

Addit:

- Select a force-using class.
- Short rest.
- Read chat and observe your character sheet.

Expected: You should regain all of your points.
Actual: You lose points.

**Comment by jyurkiw** [comment]
Forgot to check plugins first. Will double-check without them and re-file if still occuring.

**Comment by Ikaguia** [comment]
any updates on this @jyurkiw ?
