### ISSUE TITLE
Classes and Archetype Details

### ISSUE THREAD

**Issue by unrealkakeman89** [unrealkakeman89/sw5e#471]
All Classes and Archetypes have the first part of their description under the Description tab, but since we reverted the details tab back to its original form the remainder of the Class and Archetype details (the class table, features by level, and invocations) are not available anymore.
![image](https://user-images.githubusercontent.com/31608392/174857581-176b1cd1-80a6-4167-a682-3b87ac0c7326.png)
![image](https://user-images.githubusercontent.com/31608392/174857633-de31435e-71a6-45ab-9da4-4817cfb14863.png)

**Comment by Ikaguia** [comment]
Aren't those technically still available trough the advancements and invocations tabs?
