### ISSUE TITLE
Add the ability to inject logic into markdown

### ISSUE THREAD

**Issue by CatSandwich** [unrealkakeman89/sw5e#495]
I would like to see the ability to add custom logic into my custom features. I have in mind something like the following:

This custom feature deals {{ 2 * CONSULAR_LEVEL + Math.max(modifiers.charisma, modifiers.wisdom) }} damage.

Where the expression inside of the `{{   }}` is `eval`ed. I know, I know, eval is evil, but given markdown already supports adding `<script>` tags, you're not exposing any injection that isn't already possible. 

This would be a nice time saver, and could even extend to built-in features where you can do the math for the player to save them time.

For technical implementation, it could be something like (half pseudo-code): 
`markdown.replace(/{{([^}]*)}}/, (match, captured) => eval(captured))`

**Comment by CatSandwich** [comment]
Created a tiny demo if it helps at all: [https://onecompiler.com/nodejs/3ykbqpzcr](https://onecompiler.com/nodejs/3ykbqpzcr)

**Comment by Ikaguia** [comment]
I believe this was a sw5e website feature request that was mistakenly asked here, right @CatSandwich ?

**Comment by CatSandwich** [comment]
Yup that's correct
