### ISSUE TITLE
Cybernetics and Droid Customizations as Modification types

### ISSUE THREAD

**Issue by zeldafreak6245** [unrealkakeman89/sw5e#505]
Please consider adding a "Cybernetics" and "Droid Customization" option for the Modification item type. This will allow them to show up as 'Mods' within character sheets and shops in game as opposed to "Loot". Thank you! 

![image](https://user-images.githubusercontent.com/117317204/199603627-fe6133a6-7e19-4e34-87ee-9065ec3bc5c2.png)

**Comment by Ikaguia** [comment]
Added for the next beta release, tough the compendium will still be using the old style for a while
