### ISSUE TITLE
2.0.2.2.2.5 beta release errors in built zip

### ISSUE THREAD

**Issue by rikmarais** [unrealkakeman89/sw5e#513]
v`2.0.2.2.2.5` has errors in `module/applications/actor/character-orig-sheet.mjs` in the released zip file

**foundry.utilsmergeObject line 11**
![image](https://user-images.githubusercontent.com/34374883/201348881-303c25d3-535a-4968-b028-fc281821b7a0.png)
![image](https://user-images.githubusercontent.com/34374883/201348898-7bee0427-101f-4c6d-8587-e8e0762cf54e.png)
Should be `foundry.utils.mergeObject` I think

**data is not defined**
![image](https://user-images.githubusercontent.com/34374883/201351310-91d4c16e-5d3f-4b07-803a-bbbd88d7da32.png)
Should be `context.items` I think

**Missing partial**
![image](https://user-images.githubusercontent.com/34374883/201353186-c2ada8d2-448a-468f-b4d8-2cfbc9371231.png)

Currently prevents opening of PC actor sheets in the 2.0.2.2.2.5 beta for v10

**Comment by unrealkakeman89** [comment]
Commit 7d8c4ab fixes utils.mergeObject
Commit bd632dc fixes context.items
