### ISSUE TITLE
Monster Compendium Image Path Issue

### ISSUE THREAD

**Issue by eclay1819** [unrealkakeman89/sw5e#559]
**Foundry VTT Version:** 10.291
**SW5E Version:** 2.3.7
Running on RPi/Raspberry Pi OS x64

On a fresh install of SW5E, the Monster compendium isn't loading images, which seems to be due to an uppercase "...Avatar.webp", whereas the files are lowercase "...avatar.webp".

![image](https://user-images.githubusercontent.com/57675836/216853121-d216ead3-8362-4dfe-bcee-832c536ee974.png)
![image](https://user-images.githubusercontent.com/57675836/216853130-0bc79036-6e2d-4bc1-bbca-89cb5e0a59f3.png)

Looks like it possibly happened in the "System Compendium Migration" commit in the sw5e/packs/packs/monsters.db file (not sure if that file is edited directly or generated from elsewhere). The commit before that had a lowercase "...avatar.webp", then that commit seems to have changed it to "...Avatar.webp".
![image](https://user-images.githubusercontent.com/57675836/216853142-c7feb2bc-3fae-4654-93f2-f2d217a31e71.png)

My Foundry server is loaded into a different world running DnD5E ATM, but I believe there was another compendium with the same problem - Monster Temp or something like that. I'll edit this issue once I can load back into my SW5E world and confirm.

**Edit:** I looked through all of the compendiums, and the only other one that seems to be affected is Fisto's Codex. @jtljac 

Thanks for the great work, all!

**Comment by jtljac** [comment]
Fixed in #560

**Comment by jtljac** [comment]
> I edited my original comment to add this, but I probably should have just added a new comment.
> 
> The Fisto Codex compendium is also affected by this image path case issue. Should I open a new issue for that one since this is already closed?

The PR should have also fixed the issues with Fisto's Codex
