### ISSUE TITLE
Missing weapons from Wretched Hives

### ISSUE THREAD

**Issue by TheSirLancelot** [unrealkakeman89/sw5e#76]
There is missing equipment from Wretched Hives that needs to be added. Utilizing pre-existing .db from Cyr and adding to that. Will create a PR when complete.

**Comment by TheSirLancelot** [comment]
Going through the weapons.db from Cyr and making notes. Will send those to him for changes.

**Comment by TheSirLancelot** [comment]
-dupe Bo-Rifle for both modes
-flechette cannon needs attack roll removed (items to be created for ammunition since they're special)
-grenade launcher needs attack roll removed (items to be created for ammunition since they're special)
-dupe IWS for two of the three modes (blaster/sniper) and make a note in the desc to roll grenades for the antiarmor mode
-rocket launcher needs attack roll removed (items to be created for ammunition since they're special)
-torpedo launcher needs attack roll removed (items to be created for ammunition since they're special)
-vapor projector needs attack roll removed (items to be created for ammunition since they're special)
-wrist launcher needs attack roll removed (items to be created for ammunition since they're special)

**Comment by TheSirLancelot** [comment]
Cyr is making the changes to the parser for these changes. He should be making a PR once complete.

**Comment by TheSirLancelot** [comment]
P.S. I made some assumptions about the damage die for these weapons (e.g. I trusted the scraper to put the correct die in and didn't double check it)

**Comment by unrealkakeman89** [comment]
I added all weapons
